azure:
   client:
     clientId: deea87d5-4fd3-4128-baf0-51a4375698a4
     clientSecret: npIaJFwVFn2KOX7FNoAsDQ3MDEjoch+HJlWelCyJIec=
     accessTokenUri: https://login.microsoftonline.com/cegekaBlchTest.onmicrosoft.com/oauth2/token
     userAuthorizationUri: https://login.microsoftonline.com/cegekaBlchTest.onmicrosoft.com/oauth2/authorize
     clientAuthenticationScheme: form
     response_type: code id_token
     token-name: id_token     
     redirect-uri: http://localhost:8080/login
     responseMode: form_post
     resource: https://graph.windows.net
     scope: openid
     # optional parameter. possible values: login (disable SSA), none (never prompt, fail if not already logged in Azure) or consent
     prompt: login
   resource:
     userInfoUri: https://graph.windows.net/me?api-version=1.6
     jwt:
      key-uri: https://login.microsoftonline.com/cegekaBlchTest.onmicrosoft.com/discovery/v2.0/keys      

logging:
  level:
    org.springframework.security: DEBUG
