facebook:
   client:
     clientId: deea87d5-4fd3-4128-baf0-51a4375698a4
     clientSecret: npIaJFwVFn2KOX7FNoAsDQ3MDEjoch+HJlWelCyJIec=
     accessTokenUri: https://login.microsoftonline.com/cegekaBlchTest.onmicrosoft.com/oauth2/token
     userAuthorizationUri: https://login.microsoftonline.com/cegekaBlchTest.onmicrosoft.com/oauth2/authorize
     clientAuthenticationScheme: form
     response_type: code id_token
     token-name: id_token     
     redirect-uri: http://localhost:8080/login
     responseMode: form_post
     resource: http://localhost:8080/
     scope: openid
   resource:
     userInfoUri: https://graph.windows.net/me?api-version=1.6
     tokenType: code id_token
     jwt:
      key-uri: https://login.microsoftonline.com/cegekaBlchTest.onmicrosoft.com/discovery/v2.0/keys      
           
logging:
  level:
    org.springframework.security: DEBUG

    
security:
  oauth2:
    resource:
      user-info-uri: https://graph.windows.net/me?api-version=1.6
      token-info-uri: https://login.microsoftonline.com/cegekaBlchTest.onmicrosoft.com/v2.0/.well-known/openid-configuration
      jwt:
        key-uri: https://login.microsoftonline.com/cegekaBlchTest.onmicrosoft.com/discovery/v2.0/keys      
    

spring:
  resources:
    chain:
      enabled: true    